 /* Welcome Page Styles
  * --------------------------------------------------------------------- */
.ocms-welcome {
    border-collapse: collapse;
    margin: 25px 25px 40px;
}

.ocms-welcome tr {
    vertical-align: top;
}

.ocms-welcome td {
    vertical-align: top;
    padding:0;
    padding-right: 30px;
}

.ocms-welcome-header {
    height:80px;
    padding:10px;
    padding-bottom:20px;
    margin-bottom:40px;
    background-color: #F4F8E6;
    border: 1px solid #D6DDBB;
}

.ocms-welcome-section-imgdiv {
    float:left;
    vertical-align:top;
}
.ocms-welcome-section-imgdiv img {
    border: none;
    padding:0;
    padding-right:10px;
    margin-bottom:50px;
    width: 80px;
    height: 80px;
}

.ocms-welcome-section-img img {
    cursor:pointer;
}

.ocms-welcome-section h3 {
    color: #788E1E;
    font-size:115%;
}

 .ocms-welcome-section-title {
     color: #788E1E;
     text-decoration: none;
     cursor:pointer;
 }

 .ocms-welcome-section-text {
     padding-left: 20px;
 }

/* Selectable List Styles
 * --------------------------------------------------------------------- */

.ocms-selectable { list-style-type: none; margin: 0; padding: 0; width: 100%; }
.ocms-selectable li { margin: 3px; padding: 8px; height: 18px; cursor: pointer;}
