.panel{
	margin: 0;
	float: none;
	width: 100%;
	position: relative;
}

.panel h1{ 
	padding: 10px 18px 10px 12px;
	margin: 0 0 0 0; 
}

.panel-content {
	margin: 0;
	padding: 0 18px 18px 12px;
}

.panel a {
	margin: 0;
	padding: 0;
	text-decoration: none;
}

.panel a:hover {
	margin: 0;
	padding: 0;
	text-decoration: none;
	color: #000000;
}

.panel-image {
	text-align: center;
	margin: 0 Auto 10px Auto; 
}

.panel-button {
	margin: 0;
	height: 33px;
	width: 100%;
	position: relative;
}

.panel-button h1{ 
	font-size: 12pt;
	float: left;
	display: inline;
	padding: 6px 18px 0px 18px;
	margin: 0 0 0 0; 
}

.panel-expander {
	padding: 7px 10px 0 0;
	font-size: 12pt;
	text-align: right;
	float: right;
}

.top-corners{
	position: absolute; 
	top:0; 
	width: 100%
}

.top-corners .left{
	float: left;
}

.top-corners .right{
	float: right; 
}

.bottom-corners{
	position: absolute; 
	bottom:0; 
	width: 100%
}

.bottom-corners .left{
	float: left;
}

.bottom-corners .right{
	float: right; 
}

.clear {
	clear: both; 
}


