/*
 * Orchestra page preview stylesheets 
 */

.timetravelControls{
	padding: 0px; 
	background-color: #F5F5F5; 
	font-family: Arial; 
	font-size: 12px; 	
	position: absolute;
	top: 0;
	left: 0; 
	width: 100%; 
	filter:alpha(opacity=95);
	-moz-opacity:0.95;
	-khtml-opacity:0.95;
	opacity:0.85;
	z-index: 999;
	color: #000; 
 }
  	
.timetravelFooter{
	text-align: right; 
	background: none;
	font-family: Arial; 
	font-size: 12px; 
	position: absolute;
	bottom: 0;
	left: 0;  	
	filter:alpha(opacity=85);
	-moz-opacity:0.95;
	-khtml-opacity:0.95;
	opacity:0.95;
	z-index: 999;
	text-align: left;  
	margin: 0;
	padding: 0;
	width: 100%;
	color: #000; 	
}
  
.dropControl {
	width: 100%;
	text-align: center; 	
	height: 10px;
	position: relative; 
}
  
#ui-datepicker-div{
	z-index: 9999; 
}
    
#bottomVersion{
	padding: 5px;
	border-top: 1px solid rgb(200,200,200); 
	background-color: #ffffff;
}

.previewControls{
	position: relative; 
	top: 0px; 
	left: 0px;	
}

.previewControls .previewControlButtons{
	position: absolute; 
	top: 0px; 
	left: 0px; 
	z-index: 500;	
}

.previewControls .previewControlButtons img{
	display: inline !important; 	
	border: none !important;
}

.previewControls .previewControlButtons span{
	display: inline !important;
	border: none !important; 	
}

.previewControls .previewControlButtons a{
	display: inline !important; 
	font-family: arial; 
	font-size: 10px; 
	color: rgb(0,0,0); text-decoration: underline;
	border: none !important;
}

#ui-datepicker-div {
	display:none;
}

