.small-block {
	margin: 0;
	padding: 0; 
	font-size: 9pt;
	width: 247px;
	height: 164px;
}

.small-block h1{
	margin: 0px 0px 18px 0px;
	padding: 0;
}

.small-block-text{
	float: left; 
	font-size: 9pt;
	margin: 18px 10px 0px 0px;
	display: inline;
	width: 142px;
}

.small-block-image{
	margin: 14px 13px 14px 18px; 
	height: 95px;
	width: 90px; 
	border: 2px solid #FFFFFF;
	background-color: #000000;
	display: inline;
	color: #FFFFFF;
	float: left;
}